name: Trivy Security Scan

on:
  workflow_dispatch:  # Позволяет запускать вручную из Actions → Run workflow

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy security scan
        run: |
          docker run --rm aquasecurity/trivy:latest image \
            --exit-code 1 \
            --severity CRITICAL \
            grpc/go
