name: Trivy Security Scan

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy scan on grpc/go image
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: grpc/go
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          ignore-unfixed: false
