name: Trivy Security Scan

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy scan using Docker
        run: |
          docker run --rm aquasecurity/trivy:latest image --exit-code 1 --severity CRITICAL grpc/go
